mqtt:
  topic1:
    - content: someword
      key: somekey
      action: TriggerClip
      target: 42
      value: 2
    - content: someotherword
      key: somekey
      action: TriggerClip
      target: 42
      value: 3
  topic2:
    - content: clear
      action: ClearTarget
      target: 42
      value: 1
schedule:
  - name: "Event starts"
    time: "2026-06-03 11:00"
    actions:
      - action: ClearTarget
        target: 67
        value: off
      - action: TriggerClip
        target: 67
        value: 2
      - action: Opacity
        target: 67
        value: 80
  - name: "Event stops"
    time: "2026-06-03 21:00"
    actions:
      - action: Cleartarget
        target: 67
        value: 1